config/routes.rb
Rails.application.routes.draw do

 	devise_for :users
	get 'procedures/:id/select_studant' => 'procedures#select_studant', as: :select_studant_procedure
	get 'procedures/:id/selection' => 'procedures#selection', as: :selection_procedure
	get 'procedures/:id/payment' => 'procedures#payment', as: :payment_procedure
	get 'procedures/:id/registred_class' => 'procedures#registred_class', as: :procedure_class
	get 'procedures/:id/new_class' => 'procedures#new_class', as: :new_class_procedure
	get 'procedures/:id/finish' => 'procedures#finish', as: :finish_procedure
	get 'procedures/search' => 'procedures#search', as: :search_procedures
	get	'procedures/opens' => 'procedures#opens'
	get	'procedures/closeds' => 'procedures#closeds'

	get	'portions/pending' => 'portions#pending'
	get	'portions/:id/pay' => 'portions#pay', as: :pay_portion
	get 'portions/filter_date' => 'portions#filter_date'
	get 'portions/arrears' => 'portions#arrears'

	get 'studants/search' => 'studants#search', as: :search_studants

	get	'schedules/select' => 'schedules#select'
	get 'schedules/:id/new' => 'schedules#new', as: :new_schedule
	get 'schedules/:id/registred_class' => 'schedules#registred_class', as: :schedule_class
	get 'schedules/day' => 'schedules#day'
	get 'schedules/filter_date' => 'schedules#filter_date'

	get 'cashes/new_in' => 'cashes#new_in'
	get 'cashes/new_out' => 'cashes#new_out'
	get 'cashes/cash_in' => 'cashes#cash_in'
	get	'cashes/cash_out' => 'cashes#cash_out'
	get	'cashes/cash_day' => 'cashes#cash_day'
	get	'cashes/filter_date' => 'cashes#filter_date'
	get	'cashes/resume' => 'cashes#resume'
	get 'cashes/report_resume' => 'cashes#report_resume'

	get 'expenses/:id/pay' => 'expenses#pay', as: :pay_expense
	get 'expenses/filter_date' => 'expenses#filter_date'
	get	'expenses/arrears' => 'expenses#arrears'

	resources :studants, only:[:index, :new, :create, :edit, :update, :destroy, :show]
	resources :schedules, only:[:index, :edit, :update, :destroy, :show]
	resources :expenses, only:[:index, :new, :create, :destroy, :show]
	resources :cashes, only:[:index, :new, :edit, :update, :destroy, :show]
	resources :users, only:[:index, :new, :create, :edit, :update]
	resources :procedures do
		resources :portions
	end

	root 'home#index'
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :studant
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

	def index
		@schedules = Schedule.order :date_s, :hour_s
	end

	def day
		@schedules = Schedule.order :hour_s
		today = Time.zone.now
		today = today.strftime("%Y-%m-%d")
		filter = []
		@schedules.each do |schedule|
			if schedule.date_s.strftime("%Y-%m-%d") == today
				filter << schedule
			end
		end
		@schedules = filter
	end

	def new
		@studant = Studant.find(params[:id])
		@schedule = Schedule.new
		@schedule.studant_id = @studant.id
		if @studant.procedure.last != nil && @studant.procedure.last.status == 'Aberto'
			@schedule.save
		else
			@message = 'Aluno nao tem Processo Aberto'
			render 'select'
		end
	end

	def registred_class
		schedule = Schedule.find(params[:id])
		procedure = schedule.studant.procedure.last.id
		schedule.destroy

		redirect_to procedure_class_path(procedure)
	end

	def update
		@schedule = Schedule.find(params[:id])
		date = params[:date_s].to_time
		hour = params[:hour_s]
		@schedule.update(date_s: date, hour_s: hour)
		redirect_to schedules_day_path, notice: 'Agendamento Salvo!'
	end

	def filter_date
		@schedules = Schedule.all
		@select_date = params[:select_date]

		filter = []

		@schedules.each do |schedule|
			if schedule.date_s.strftime("%Y-%m-%d") == @select_date
				filter << schedule
			end
		end
		@schedules = filter
	end

	def destroy
		id = params[:id]
		Schedule.destroy id
		redirect_to schedules_path, notice: 'Agendamento Excluído!'
	end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_schedules.html.erb
<div>
	<table class="table table-bordered">
		<thead>
			<th>Data</th>
			<th>Hora</th>
			<th>Aluno</th>
			<th>Telefone</th>
		</thead>
		<tbody>
			<% @schedules.each do |schedule| %>
			<tr>
				<td><%= datebr(schedule.date_s) %></td>
				<td><%= schedule.hour_s %></td>
				<td><%= schedule.studant.name %></td>
				<td><%= schedule.studant.fone %></td>
				<td width="12%"><%= link_to 'registrar aula', schedule_class_path(schedule), class: 'btn btn-success' %></td>
				<td width="8%"><%= link_to 'excluir', schedule_path(schedule), method: :delete, class: 'btn btn-danger', data:{confirm: 'Deseja excluir agendamento?'} %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/schedules/day.html.erb
<div class="label">
	<span>Agendamentos do Dia</span>
</div>

<%= render 'schedules' %>

app/views/schedules/filter_date.html.erb
<div class="label">
	<span>Agendamentos</span>
</div>

<%= form_tag schedules_filter_date_path, method: :get, class: 'navbar-form navbar-right' do %>
	<div>
		<input type="button" value="Voltar" onclick="history.go(-1)" class="btn btn-default">
		<%= date_field_tag :select_date, @select_date, class: 'form-control' %>
	</div>
<% end %>

<%= render 'schedules' %>

app/views/schedules/index.html.erb
<div class="label">
	<span>Agendamentos</span>
</div>

<%= form_tag schedules_filter_date_path, method: :get, class: 'navbar-form navbar-right' do %>
	<div>
		<%= date_field_tag :select_date, nil, class: 'form-control' %>
		<%= button_to 'Filtrar', nil, class: 'btn btn-success' %>
	</div>
<% end %>

<%= render 'schedules' %>

app/views/schedules/new.html.erb
<div class="label">
	<span>Novo Agendamento</span>
</div>

<div>
	<%= form_for @schedule do |f| %>
		<div>
			<%= f.label :aluno %>
			<%= text_field_tag :studant, @studant.name, class: 'form-control' %>
		</div><br>
		<div>
			<%= f.label :data %>
			<%= date_field_tag :date_s, nil, class: 'form-control' %>
		</div><br>
		<div>
			<%= f.label :hora %>
			<%= time_field_tag :hour_s, nil, class: 'form-control' %>
		</div><br>
		<div>
			<%= f.submit :salvar, class: 'btn btn-success' %>
		</div>
	<% end %>
</div>

app/views/schedules/select.html.erb
<% if @message %>
	<div class="alert alert-danger">
		<%= @message %>
	</div>
<% end %>

<div class="label">
	<span>Selecione o Aluno</span>
</div>

<div class="form-center">
	<%= form_tag search_studants_path, method: :get, class: 'form-group' do %>
		<div>
			<%= text_field_tag :name, @name, class: 'form-control' %><br>
			<%= button_to :buscar, nil, class: 'btn btn-success' %>
		</div>
	<% end %>
</div>