config/routes.rb
Rails.application.routes.draw do

 	devise_for :users
	get 'procedures/:id/select_studant' => 'procedures#select_studant', as: :select_studant_procedure
	get 'procedures/:id/selection' => 'procedures#selection', as: :selection_procedure
	get 'procedures/:id/payment' => 'procedures#payment', as: :payment_procedure
	get 'procedures/:id/registred_class' => 'procedures#registred_class', as: :procedure_class
	get 'procedures/:id/new_class' => 'procedures#new_class', as: :new_class_procedure
	get 'procedures/:id/finish' => 'procedures#finish', as: :finish_procedure
	get 'procedures/search' => 'procedures#search', as: :search_procedures
	get	'procedures/opens' => 'procedures#opens'
	get	'procedures/closeds' => 'procedures#closeds'

	get	'portions/pending' => 'portions#pending'
	get	'portions/:id/pay' => 'portions#pay', as: :pay_portion
	get 'portions/filter_date' => 'portions#filter_date'
	get 'portions/arrears' => 'portions#arrears'

	get 'studants/search' => 'studants#search', as: :search_studants

	get	'schedules/select' => 'schedules#select'
	get 'schedules/:id/new' => 'schedules#new', as: :new_schedule
	get 'schedules/:id/registred_class' => 'schedules#registred_class', as: :schedule_class
	get 'schedules/day' => 'schedules#day'
	get 'schedules/filter_date' => 'schedules#filter_date'

	get 'cashes/new_in' => 'cashes#new_in'
	get 'cashes/new_out' => 'cashes#new_out'
	get 'cashes/cash_in' => 'cashes#cash_in'
	get	'cashes/cash_out' => 'cashes#cash_out'
	get	'cashes/cash_day' => 'cashes#cash_day'
	get	'cashes/filter_date' => 'cashes#filter_date'
	get	'cashes/resume' => 'cashes#resume'
	get 'cashes/report_resume' => 'cashes#report_resume'

	get 'expenses/:id/pay' => 'expenses#pay', as: :pay_expense
	get 'expenses/filter_date' => 'expenses#filter_date'
	get	'expenses/arrears' => 'expenses#arrears'

	resources :studants, only:[:index, :new, :create, :edit, :update, :destroy, :show]
	resources :schedules, only:[:index, :edit, :update, :destroy, :show]
	resources :expenses, only:[:index, :new, :create, :destroy, :show]
	resources :cashes, only:[:index, :new, :edit, :update, :destroy, :show]
	resources :users, only:[:index, :new, :create, :edit, :update]
	resources :procedures do
		resources :portions
	end

	root 'home#index'
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :studant
  has_many :portion, dependent: :destroy
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
	
	def opens
		@procedures = Procedure.where(status: 'Aberto')
	end

	def closeds
		@procedures = Procedure.where(status: 'Concluido')
	end

	def index
		@procedures = Procedure.all
	end

	def new
		@procedure = Procedure.new
		@procedure.studant_id = Studant.first.id
		@procedure.class_a = 0
		@procedure.class_b = 0
		@procedure.class_t = 0
		@procedure.save
		redirect_to select_studant_procedure_path(@procedure)
	end

	def selection
		@procedure = Procedure.find(params[:id])
		cpf = params[:cpf]
		studant = Studant.where "cpf like ?", "%#{cpf}%"

		if studant.empty?
			render :select_studant
		else
			@procedure.update(studant_id: studant.first.id)
			redirect_to edit_procedure_path
		end
	end

	def edit
		@procedure = Procedure.find(params[:id])
	end

	def update
		@procedure = Procedure.find(params[:id])
		values = params.require(:procedure).permit!
		@procedure.update values

		if @procedure.portion.first != nil
			redirect_to procedures_path, notice: 'Processo Alterado com Sucesso!'
		else
			redirect_to payment_procedure_path(@procedure)
		end
	end

	def search
		@name = params[:name]
		@name.upcase!
		studant = Studant.where "name like ?", "%#{@name}%"
		studant = studant.first
		@procedures = Procedure.where(studant_id: studant.id)
	end

	def payment
		@procedure = Procedure.find(params[:id])
	end

	def registred_class
		@procedure = Procedure.find(params[:id])
		if @procedure.category == 'A'
			@options = ['A', 'Teorica']
		elsif @procedure.category == 'B'
			@options = ['B', 'Teorica']
		else
			@options = ['A', 'B', 'Teorica']
		end
	end

	def new_class
		@procedure = Procedure.find(params[:id])
		category = params[:category]
		hours = params[:hours]
		hours = hours.to_f

		if category == 'A'
			total_hours = @procedure.class_a + hours
			@procedure.update(class_a: total_hours)
		elsif category == 'B'
			total_hours = @procedure.class_b + hours
			@procedure.update(class_b: total_hours)
		else
			total_hours = @procedure.class_t + hours
			@procedure.update(class_t: total_hours)
		end

		@procedure.save
		redirect_to procedure_path(@procedure), notice: 'Aula Registrada com Sucesso!'

	end

	def finish
		@procedure = Procedure.find(params[:id])
		@procedure.update(status: 'Concluido')

		redirect_to procedure_path(@procedure), notice: 'Processo Finalizado com Sucesso!'
	end
	
	def destroy
		id = params[:id]
		Procedure.destroy id

		redirect_to procedures_path, notice: 'Processo Excluido com Sucesso!'
	end

	def show
		@procedure = Procedure.find(params[:id])
		@portions = Portion.where(procedure_id: @procedure.id)

		if @procedure.portion.last.status != 'pago'
			respond_to do |format|
				format.html
				format.pdf {render template: 'procedures/print', pdf: 'print'}
			end
		else
			respond_to do |format|
				format.html
				format.pdf {render template: 'procedures/print_receipt', pdf: 'print_receipt'}
			end
		end
	end
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form_procedure.html.erb
<div class="form-center">
	<div class="form-group">
			<%= label_tag :aluno %>
			<%= text_field_tag :studant, @procedure.studant.name, class: 'form-control' %>
	</div>

	<%= form_for @procedure do |f| %>

		<div class="form-group">
			<%= f.label 'Numero do Processo' %>
			<%= f.text_field :number, class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label 'Vencimento do Processo' %>
			<%= f.date_field :due_date, class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label :categoria %><br>
			<%= f.select :category, ['A', 'B', 'AB'] %>
		</div>

		<div class="form-group">
			<%= f.label :situação %><br>
			<%= f.select :status, ['Aberto', 'Concluido'] %>
		</div>

		<div class="form-group">
			<%= f.submit :salvar, class: 'btn btn-success' %>
		</div>
	<% end %>
</div>

app/views/procedures/_procedures.html.erb
<table class="table table-bordered">
	<thead>
		<th>Numero</th>
		<th>Aluno</th>
		<th>Categoria</th>
		<th>Status</th>
	</thead>
	<tbody>
		<% @procedures.each do |procedure| %>
		<tr>
			<td><%= procedure.number %></td>
			<td><%= procedure.studant.name %></td>
			<td><%= procedure.category %></td>
			<td><%= procedure.status %></td>
			<td width="8%"><%= link_to 'Exibir', procedure_path(procedure), class: 'btn btn-primary' %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/procedures/class.html.erb
<div class="label">
	<span>Registrar Aula</span>
</div>

<div class="form-center">

	<%= form_tag new_class_procedure_path, method: :get do %>

		<div class="form-group">
			<%= label_tag :category %><br>
			<%= select_tag :category, options_for_select(['A', 'B', 'Teorica']) %>
		</div>

		<div class="form-group">
			<%= label_tag :hours %>
			<%= number_field_tag :hours, 0, class: 'form-control' %>
		</div>

		<div>
			<%= button_to :salvar, nil, class: 'btn btn-success' %>
		</div>
	<% end %>

</div>

app/views/procedures/closeds.html.erb
<div class="label">
	<span>Processos Concluidos</span>
</div>

<div>
	<%= form_tag search_procedures_path, method: :get, class: 'navbar-form navbar-right' do %>
		<div>
			<%= text_field_tag :name, nil, class: 'form-control' %>
			<%= button_to :buscar, nil, class: 'btn btn-success' %>
		</div>
	<% end %>
</div>

<%= render 'procedures' %>

app/views/procedures/edit.html.erb
<div class="label">
	<span>Alterar Processo</span>
</div>

<%= render 'form_procedure' %>

app/views/procedures/index.html.erb
<div class="label">
	<span>Processos</span>
</div>

<table class="table table-bordered">
	<thead>
		<th>Numero</th>
		<th>Aluno</th>
		<th>Categoria</th>
		<th>Status</th>
	</thead>
	<tbody>
		<% @procedures.each do |procedure| %>
		<tr>
			<td><%= procedure.number %></td>
			<td><%= procedure.studant.name %></td>
			<td><%= procedure.category %></td>
			<td><%= procedure.status %></td>
			<td><%= link_to 'Exibir', procedure_path(procedure), class: 'btn btn-primary' %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/procedures/opens.html.erb
<div class="label">
	<span>Processos Abertos</span>
</div>

<div>
	<%= form_tag search_procedures_path, method: :get, class: 'navbar-form navbar-right' do %>
		<div>
			<%= text_field_tag :name, nil, class: 'form-control' %>
			<%= button_to :buscar, nil, class: 'btn btn-success' %>
		</div>
	<% end %>
</div>

<%= render 'procedures' %>

app/views/procedures/payment.html.erb
<div class="label">
	<span>Pagamento</span>
</div>

<div class="form-center">
	<%= form_tag new_procedure_portion_path(@procedure), method: :get do %>
		
		<div class="form-group">
			<%= label_tag 'Forma de Pagamento' %>
			<%= select_tag :payment, options_for_select(['parcelado', 'a vista']), class: 'form-control', id: "options", onchange: "optionCheck()" %>
		</div>

		<div id="hiddenDiv">
			<div class="form-group">
				<%= label_tag 'Numero de Parcelas' %>
				<%= number_field_tag :number_portions, nil, class: 'form-control' %>
			</div>

			<div class="form-group">
				<%= label_tag 'Vencimento' %>
				<%= date_field_tag :due_date, nil, class: 'form-control' %>
			</div>
		</div>

		<div class="form-group">
			<%= label_tag 'Valor Total' %>
			<%= text_field_tag :total, nil, class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= button_to :finalizar, nil, class: 'btn btn-success' %>
		</div>

	<% end %>
</div>

<script type="text/javascript">
    function optionCheck(){
        var option = document.getElementById("options").value;
        if(option == "parcelado"){
            document.getElementById("hiddenDiv").style.visibility ="visible";
        }
        if(option == "a vista"){
            document.getElementById("hiddenDiv").style.visibility ="hidden";
        }
    }
</script>

app/views/procedures/print.pdf.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>carnê</title>
	<style type="text/css">

		.portion {
			width: 100%;
			float: left;
		}

		.left {
			width: 40%;
			float: left;
			margin-bottom: 2.5em;
		}

		.right {
			float: left;
			width: 55%;
			border-left: solid 1px;
			padding-left: 2em;
			margin-bottom: 2.5em;
		}

		.division {
			margin: 0;
			margin-bottom: 1em;
			padding: 0;
			float: left;
			width: 100%;
		}

		label {
			font-weight: bold;
		}
	</style>
</head>
<body>
	<% @procedure.portion.each do |portion| %>

		<div class="portion">
			<div class="left">
				<p><%= wicked_pdf_image_tag 'banner.png', :width => '100px' %></p>
				<label>Nº</label>
				<span><%=portion.id %></span><br><br>
				<label>ALUNO:</label>
				<span><%= @procedure.studant.name %></span><br><br>
				<label>CPF:</label>
				<span><%= @procedure.studant.cpf %></span><br><br>
				<label>PROCESSO:</label>
				<span><%= @procedure.number %></span><br><br>
				<label>VENCIMENTO:</label>
				<span><%= datebr(portion.due_date) %></span><br><br>
				<label>VALOR:</label>
				<span><%= number_to_currency portion.price %></span>
				<p>*Pagavel Apenas na Auto Escola</p>
				<label>DATA:</label>
				<span>____/____/_________</span><br><br>
			</div>
			<div class="right">
				<p><%= wicked_pdf_image_tag 'banner.png', :width => '100px' %></p>
				<label>Nº</label>
				<span><%=portion.id %></span><br><br>
				<label>ALUNO:</label>
				<span><%= @procedure.studant.name %></span><br><br>
				<label>CPF:</label>
				<span><%= @procedure.studant.cpf %></span><br><br>
				<label>PROCESSO:</label>
				<span><%= @procedure.number %></span><br><br>
				<label>VENCIMENTO:</label>
				<span><%= datebr(portion.due_date) %></span><br><br>
				<label>VALOR:</label>
				<span><%= number_to_currency portion.price %></span>
				<p>*Pagavel Apenas na Auto Escola</p>
				<label>DATA:</label>
				<span>____/____/_________</span><br><br>
			</div>
		</div>
	<% end %>
</body>
</html>

app/views/procedures/print_receipt.pdf.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Recipo</title>
	</head>
	<body>
		<div  style="width: 90%; margin: 0 auto;">
			<%= wicked_pdf_image_tag 'banner.png', :width => '200px' %>
			<h2 align="center">RECIBO</h2>

			<p>Recebemos do(a) Aluno(a) <b><%= @procedure.studant.name.upcase %></b> a importância de <%= number_to_currency @procedure.portion.last.price %> referente ao pagamento do processo de habilitação. </p>
			<p>Para maior clareza firmo o presente.</p><br>

			<p align="center">São Raimundo Nonato-PI, <%= datebr(Time.zone.now) %></p><br><br><br>

			<p align="center">___________________________________________________________</p>
			<p align="center">Auto Escola Jenipapo</p>
		</div>

	</body>
</html>

app/views/procedures/registred_class.html.erb
<div class="label">
	<span>Registrar Aula</span>
</div>

<div class="form-center">

	<%= form_tag new_class_procedure_path, method: :get do %>

		<div class="form-group">
			<%= label_tag :category %><br>
			<%= select_tag :category, options_for_select(@options) %>
		</div>

		<div class="form-group">
			<%= label_tag :hours %>
			<%= number_field_tag :hours, 0, class: 'form-control' %>
		</div>

		<div>
			<%= button_to :salvar, nil, class: 'btn btn-success' %>
		</div>
	<% end %>

</div>

app/views/procedures/search.html.erb
<div class="label">
	<span>Busca de Processos</span>
</div>

<div>
	<%= form_tag search_procedures_path, method: :get, class: 'navbar-form navbar-right' do %>
		<div>
			<input type="button" value="Voltar" onclick="history.go(-1)" class="btn btn-default">
			<%= text_field_tag :name, @name, class: 'form-contorl' %>
		</div>
	<% end %>
</div>

<%= render 'procedures' %>

app/views/procedures/select_studant.html.erb
<div class="label">
	<span>Informe o Aluno</span>
</div>

<div class="form-center">
	<%= form_tag search_studants_path, method: :get, class: 'navbar-form' do %>
		<div style="text-align: right;">
			<%= text_field_tag :name, @name, class: 'form-control' %>
			<%= button_to :buscar, nil, class: 'btn btn-success' %>
		</div>
	<% end %>

	<%= form_tag selection_procedure_path, method: :get do %>
		<div>
			<%= label_tag :cpf %>
			<%= text_field_tag :cpf, nil, class: 'form-control' %>
		</div><br>
		<div>
			<%= button_to :selecionar, nil, class: 'btn btn-success' %>
		</div>
	<% end %>
</div>

app/views/procedures/show.html.erb
<div class="label">
	<span>Processo: <%= @procedure.number %></span>
</div>

<div class="form-center">
	<div class="options">
		<span><%= link_to 'Todos Processos', procedures_path, class: 'btn btn-default' %></span>
		<span><%= link_to 'Editar', edit_procedure_path(@procedure), class: 'btn btn-primary' %></span>
		<span><%= link_to 'Fez Aula', procedure_class_path(@procedure), class: 'btn btn-warning' %></span>
		<% if @procedure.status == 'Aberto' %>
			<span><%= link_to 'Finalizar Processo', finish_procedure_path(@procedure), class: 'btn btn-success' %></span>
		<% end %>
		<span><%= link_to 'Excluir', procedure_path(@procedure), method: :delete, class: 'btn btn-danger', data:{confirm: 'Deseja Excluir o Processo?'} %></span>
		<span><%= link_to (image_tag 'imprimir.png', :width => '40px', :height => '40px'), "#{@procedure.id}.pdf" %></span>
	</div>
	<div class="form-group">
		<%= label_tag :aluno %>
		<%= text_field_tag :studant, @procedure.studant.name, :disabled=>true, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= label_tag 'Numero do Processo' %>
		<%= text_field_tag :number, @procedure.number, :disabled=>true, class: 'form-control' %>
	</div>
	<div class="form-group">
		<% if @procedure.due_date != nil %>
			<% if datebr(@procedure.due_date) < (due = Time.zone.now + 60.day) %>
				<div class="alert alert-danger">
					<span>Atenção! Processo Esta Perto do Vencimento!</span>
				</div>
			<% end %>
		<% end %>
		<%= label_tag 'Vencimento do Processo' %>
		<% if @procedure.due_date != nil %>	
			<%= text_field_tag :due_date, datebr(@procedure.due_date), :disabled=>true, class: 'form-control' %>
		<% end %>
	</div>
	<div class="form-group">
		<%= label_tag :categoria %>
		<%= text_field_tag :category, @procedure.category, :disabled=>true, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= label_tag :situacao %>
		<%= text_field_tag :status, @procedure.status, :disabled=>true, class: 'form-control' %>
	</div>

	<div class="card"> 
		<%= label_tag 'Horas de Aula' %><br>
		<% if @procedure.category == 'A' || @procedure.category == 'AB' %>
			<span style="font-weight: bold;">Categ. A:</span>
			<%= @procedure.class_a %>h<br>
		<% end %>
		<% if @procedure.category == 'B' || @procedure.category == 'AB' %>
			<span style="font-weight: bold;">Categ. B:</span>
			<%= @procedure.class_b %>h<br>
		<% end %>
		<span style="font-weight: bold;">Teórica:</span>
		<%= @procedure.class_t %>h
	</div><br>

	<%= label_tag :Parcelas %>
	<div>
		<table class="table table-bordered">
			<thead>
				<th>Vencimento</th>
				<th>Valor</th>
				<th>Status</th>
			</thead>
			<tbody>
				<% @portions.each do |portion| %>
				<tr>
					<td><%= datebr(portion.due_date) %></td>
					<td><%= number_to_currency portion.price %></td>
					<td><%= portion.status %></td>
					<td width="8%"><%= link_to 'Excluir', procedure_portion_path(@procedure, portion), method: :delete, class: 'btn btn-danger' %></td>
					<td width="8%"><%= link_to 'Editar', edit_procedure_portion_path(@procedure, portion), class: 'btn btn-warning' %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>