config/routes.rb
Rails.application.routes.draw do

 	devise_for :users
	get 'procedures/:id/select_studant' => 'procedures#select_studant', as: :select_studant_procedure
	get 'procedures/:id/selection' => 'procedures#selection', as: :selection_procedure
	get 'procedures/:id/payment' => 'procedures#payment', as: :payment_procedure
	get 'procedures/:id/registred_class' => 'procedures#registred_class', as: :procedure_class
	get 'procedures/:id/new_class' => 'procedures#new_class', as: :new_class_procedure
	get 'procedures/:id/finish' => 'procedures#finish', as: :finish_procedure
	get 'procedures/search' => 'procedures#search', as: :search_procedures
	get	'procedures/opens' => 'procedures#opens'
	get	'procedures/closeds' => 'procedures#closeds'

	get	'portions/pending' => 'portions#pending'
	get	'portions/:id/pay' => 'portions#pay', as: :pay_portion
	get 'portions/filter_date' => 'portions#filter_date'
	get 'portions/arrears' => 'portions#arrears'

	get 'studants/search' => 'studants#search', as: :search_studants

	get	'schedules/select' => 'schedules#select'
	get 'schedules/:id/new' => 'schedules#new', as: :new_schedule
	get 'schedules/:id/registred_class' => 'schedules#registred_class', as: :schedule_class
	get 'schedules/day' => 'schedules#day'
	get 'schedules/filter_date' => 'schedules#filter_date'

	get 'cashes/new_in' => 'cashes#new_in'
	get 'cashes/new_out' => 'cashes#new_out'
	get 'cashes/cash_in' => 'cashes#cash_in'
	get	'cashes/cash_out' => 'cashes#cash_out'
	get	'cashes/cash_day' => 'cashes#cash_day'
	get	'cashes/filter_date' => 'cashes#filter_date'
	get	'cashes/resume' => 'cashes#resume'
	get 'cashes/report_resume' => 'cashes#report_resume'

	get 'expenses/:id/pay' => 'expenses#pay', as: :pay_expense
	get 'expenses/filter_date' => 'expenses#filter_date'
	get	'expenses/arrears' => 'expenses#arrears'

	resources :studants, only:[:index, :new, :create, :edit, :update, :destroy, :show]
	resources :schedules, only:[:index, :edit, :update, :destroy, :show]
	resources :expenses, only:[:index, :new, :create, :destroy, :show]
	resources :cashes, only:[:index, :new, :edit, :update, :destroy, :show]
	resources :users, only:[:index, :new, :create, :edit, :update]
	resources :procedures do
		resources :portions
	end

	root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cash.rb
class Cash < ApplicationRecord
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/models/portion.rb
class Portion < ApplicationRecord
  belongs_to :procedure
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :studant
  has_many :portion, dependent: :destroy
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :studant
end

app/models/studant.rb
class Studant < ApplicationRecord
	has_many :procedure
	has_many :schedule

	validates :name, presence: true
	validates :cpf, presence: true
	validates :fone, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cashes_controller.rb
class CashesController < ApplicationController

	def index
		@cashes = Cash.all
	end

	def cash_in
		@cashes = Cash.where(category: 'Receita')
		@category = 'Receita'
	end

	def cash_out
		@cashes = Cash.where(category: 'Despesa')
		@category = 'Despesa'
	end

	def cash_day
		@cashes_in = Cash.where(category: "Receita")
		@cashes_in = filter_day(@cashes_in)
		@cashes_out = Cash.where(category: "Despesa")
		@cashes_out = filter_day(@cashes_out)
	end

	def new_in
		@cash = Cash.new
		@cash.category = 'Receita'
		@cash.save
		redirect_to edit_cash_path(@cash)
	end

	def new_out
		@cash = Cash.new
		@cash.category = 'Despesa'
		@cash.save
		redirect_to edit_cash_path(@cash)
	end

	def edit
		@cash = Cash.find(params[:id])
	end

	def update
		@cash = Cash.find(params[:id])
		values = params.require(:cash).permit!
		@cash.update values
		redirect_to cashes_path
	end

	def filter_date
		@cashes = Cash.where(category: params[:category])
		@begin_date = params[:begin_date]
		@end_date = params[:end_date]

		filter = []

		if @begin_date <= @end_date
			@cashes.each do |cash|
				if cash.created_at.strftime("%Y-%m-%d") == @begin_date
					filter << cash
				elsif cash.created_at.strftime("%Y-%m-%d") > @begin_date && cash.created_at.strftime("%Y-%m-%d") < @end_date
					filter << cash
				elsif cash.created_at.strftime("%Y-%m-%d") == @end_date
					filter << cash
				end
			end
			@cashes = filter
		end
	end

	def report_resume
		@cashes = Cash.all
		@begin_date = params[:begin_date]
		@end_date = params[:end_date]

		@cashes_in = []
		@total_cashes_in = 0
		@cashes_out = []
		@total_cashes_out = 0

		if @begin_date <= @end_date
			@cashes.each do |cash|
				if cash.created_at.strftime("%Y-%m-%d") == @begin_date
					if cash.category == 'Receita'
						@cashes_in << cash
						if cash.price != nil
							@total_cashes_in += cash.price
						end
					else
						@cashes_out << cash
						if cash.price != nil
							@total_cashes_out += cash.price
						end	
					end
				elsif cash.created_at.strftime("%Y-%m-%d") > @begin_date && cash.created_at.strftime("%Y-%m-%d") < @end_date
					if cash.category == 'Receita'
						@cashes_in << cash
						if cash.price != nil
							@total_cashes_in += cash.price
						end
					else
						@cashes_out << cash
						if cash.price != nil
							@total_cashes_out += cash.price
						end	
					end
				elsif cash.created_at.strftime("%Y-%m-%d") == @end_date
					if cash.category == 'Receita'
						@cashes_in << cash
						if cash.price != nil
							@total_cashes_in += cash.price
						end
					else
						@cashes_out << cash
						if cash.price != nil
							@total_cashes_out += cash.price
						end	
					end
				end
			end
		end

		@total_resume = @total_cashes_in - @total_cashes_out
	end

	def destroy
		id = params[:id]
		Cash.destroy id

		redirect_to cashes_path, notice: 'apagado com sucesso!'
	end

	private

	def filter_day(base)
		today = Time.zone.now
		today = today.strftime("%Y-%m-%d")
		filter = []
		base.each do |b|
			if b.created_at.strftime("%Y-%m-%d") == today
				filter << b
			end
		end
		base = filter
		base.sort!
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def edit
		@user = current_user
	end

	def update
		user = User.find(params[:id])
		password = params[:password]
		if password != ''
			user.update(password: password)
			redirect_to root_path, notice: 'Alterado com Sucesso!'
		else
			render :edit
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def datebr(date)
		date = date.strftime("%d/%m/%Y")
		date
	end

	def hourbr(hour)
		hour = hour.strftime("%H:%M")
		hour
	end

end

app/helpers/cashes_helper.rb
module CashesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portions_helper.rb
module PortionsHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/studants_helper.rb
module StudantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CFC Jenipapo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="primary">
      <header>
        <input type="checkbox" id="bt_menu">
        <label for="bt_menu">&#9776;</label>

        <span style="float: left; padding: 4px 2em;"><%= link_to (image_tag 'logo.png', :width => '100px'), root_path %></span>
        <nav class="menus"> <!-- Menu de Navegação -->

          <% if signed_in? %>
            <ul>

              <li><a href="">Alunos</a>
                <ul>
                  <li><%= link_to 'Cadastrar Aluno', new_studant_path %></li>
                  <li><%= link_to 'Todos', studants_path %></li>
                </ul>
              </li>
              <li><a href="">Processos</a>
                <ul>
                  <li><%= link_to 'Novo Processo', new_procedure_path, data:{confirm: 'Registrar Novo Processo?'} %></li>
                  <li><%= link_to 'Abertos', procedures_opens_path %></li>
                  <li><%= link_to 'Concluidos', procedures_closeds_path %></li>
                  <li><%= link_to 'Todos', procedures_path %></li>
                </ul>
              </li>
              <li><a href="">Agendamentos</a>
                <ul>
                  <li><%= link_to 'Agendar Aluno', schedules_select_path %></li>
                  <li><%= link_to 'Agend. do Dia', schedules_day_path %></li>
                  <li><%= link_to 'Todos Agend.', schedules_path %></li>
                </ul>
              </li>
              <li><a href="">Contas</a>
                <ul>
                  <li><%= link_to 'A Pagar', expenses_path %></li>
                  <li><%= link_to 'A Receber', portions_pending_path %></li>
                  <li><%= link_to 'Nova Despesa', cashes_new_out_path, data:{confirm: 'Registrar Nova Despesa?'} %></li>
                  <li><%= link_to 'Nova Receita', cashes_new_in_path, data:{confirm: 'Registrar Nova Receita?'} %></li>
                </ul>
              </li>
              <li><a href="">Relatorios</a>
                <ul>
                  <li><%= link_to 'Parcel. em Atraso', portions_arrears_path %></li>
                  <li><%= link_to 'Contas em Atraso', expenses_arrears_path %></li>
                  <li><%= link_to 'Receitas', cashes_cash_in_path %></li>
                  <li><%= link_to 'Despesas', cashes_cash_out_path %></li>
                  <li><%= link_to 'Caixa do Dia', cashes_cash_day_path %></li>
                  <li><%= link_to 'Resumo Período', cashes_resume_path %></li>
                </ul>
              </li>
              <li><a href="">Usuários</a>
                <ul>
                  <li><%= link_to 'Alterar Senha', edit_user_path(current_user) %></li>
                </ul>
              </li>

              <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
            <% end %>
          </ul>

        </nav> <!-- fim do Menu -->
      </header>
      

      <div class="primary-container">

        <% if flash[:notice] %>
          <div class="alert alert-info" role="alert">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <%= yield %>
      </div>

      <footer class="footer">
          <h4>Auto Escola Jenipapo</h4>
          <p>&copy; Todos os direitos reservados</p>
      </footer>
    </div>
    
    
  </body>
</html>